import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import athi from "../public/avatar.png";
import java from "../public/java.png";
import javascript from "../public/js.png";
import html from "../public/html.png";
import css from "../public/css.png";
import python from "../public/python.png";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Athenkosi Nomavila Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10 bg-sky-100 sm:px-10 md:px-20 lg:px-96">
        <section className="bg-gradient-to-b from-blue-300 to-purple-300">
          <section>
            <nav className="py-10  flex justify-between">
              <div className="text-5xl lg:text-6xl flex justify-center gap-10 pl-5  py-2 text-gray-800">
                <a href="https://github.com/Athenkosi-Nomavila/">
                  <AiFillGithub />
                </a>

                <a href="https://www.linkedin.com/in/athenkosi-nomavila">
                  <AiFillLinkedin />
                </a>
              </div>
              <button
                onClick={() => setDarkMode(!darkMode)}
                className="text-2xl px-4 py-2 bg-gray-200 dark:bg-gray-800 rounded"
              >
                {darkMode ? "Light" : "Dark"} Mode
              </button>
            </nav>
            <div className="text-center shadow-2xl py-20">
              <h2 className="text-5xl p-10 py-2 text-blue-500 dark:text-blue-600 font-medium lg:text-8xl md:text-6xl">
                Athenkosi Nomavila
              </h2>
              <h3 className="text-2xl p-10 py-2 lg:text-6xl md:text-3xl">
                Fullstack Developer
              </h3>
              <div className="relative mx-auto bg-orange-200 rounded-full w-80 h-80 overflow-hidden lg:h-fit lg:w-fit">
                <Image src={athi} alt="Athenkosi Nomavila" />
              </div>
            </div>
          </section>

          <section className="shadow-2xl text-center  p-10 py-10">
            <div>
              <h2 className="text-5xl pt-20 py-2 font-medium lg:text-8xl md:text-6xl">
                About
              </h2>
              <p className="text-md py-5 leading-8 text-gray-800 max-w-3xl mx-auto lg:text-2xl md:text-xl pb-20">
                I am a young software developer looking to challenge myself in
                different aspects of life. I am set to graduate from We Think Code
                after completing my software development studies. I chose this
                career due to my passion for technology and my desire to make a
                positive impact on the world. Through my studies, I have been
                exposed to diverse individuals with varied perspectives, which has
                reinforced my belief in the power of community and teamwork.
                These values can be applied to improve workplaces, South Africa,
                and beyond.
              </p>
            </div>
          </section>

          <section className="shadow-2xl pb-10 text-center">
            <div className="text-center pt-20">
              <h2 className="text-5xl font-medium lg:text-8xl md:text-6xl">
                Skills
              </h2>
            </div>
            <div className="mx-auto w-20 h-20 mt-5 md:h-46 md:w-46">
              <h2 className=" font-bold ">Java</h2>
              <Image src={java} alt="Java logo" />
            </div>

            <div className="mx-auto w-20 h-20 mt-5 md:h-46 md:w-46">
              <h2 className=" font-bold ">Javascript</h2>
              <Image src={javascript} alt="JavaScript logo" />
            </div>

            <div className="mx-auto w-20 h-20 mt-7 md:h-46 md:w-46">
              <h2 className=" font-bold ">HTML</h2>
              <Image src={html} alt="HTML logo" />
            </div>

            <div className="mx-auto w-20 h-20 mt-4 md:h-46 md:w-46">
              <h2 className=" font-bold ">CSS</h2>
              <Image src={css} alt="CSS logo" />
            </div>

            <div className=" mx-auto w-20 h-20 mt-4 md:h-46 md:w-46">
              <h2 className=" font-bold ">Python</h2>
              <Image src={python} alt="Python logo" />
            </div>
          </section>

          <section className="shadow-2xl p-10 py-10">
            <div className="text-center">
              <h2 className="text-5xl pt-20 py-2 font-medium lg:text-8xl md:text-6xl">
                Projects
              </h2>
              <p className="text-md py-5 leading-8 text-gray-800 max-w-3xl mx-auto md:text-xl pb-20 lg:text-2xl">
                These are the projects I am most proud of. Throughout my journey
                in making them, I faced numerous challenges that pushed me out of
                my comfort zone and encouraged innovative thinking. This
                experience has led to significant personal growth, and I believe
                it is only the beginning.
              </p>

              <div className="loom">
                <iframe
                  src="https://www.loom.com/embed/9766a9278ac24dacbbd21cbf1a113f87?sid=9de22041-2f95-405d-b6fb-81056039b9e8"
                  frameborder="0"
                  webkitallowfullscreen
                  mozallowfullscreen
                  allowfullscreen
                  className="loom-frame"
                ></iframe>
              </div>

              <div className="loom">
                <iframe
                  src="https://www.loom.com/embed/19d66eb756724041b496459f667802ca?sid=ba357b58-3a65-4c66-bcdf-8660b2bbbfaf"
                  frameborder="0"
                  webkitallowfullscreen
                  mozallowfullscreen
                  allowfullscreen
                  className="loom-frame"
                ></iframe>
              </div>

              <div className="loom">
                <iframe
                  src="https://www.loom.com/embed/3c2f2ca01b4c40bbae6922d616a3895d?sid=8846f3bd-96fb-453e-9738-f663eda3cc04"
                  frameborder="0"
                  webkitallowfullscreen
                  mozallowfullscreen
                  allowfullscreen
                  className="loom-frame"
                ></iframe>
              </div>

              <div className="loom">
                <iframe
                  src="https://www.loom.com/embed/21fdda05d04643ce86dc354c4f344e91"
                  frameborder="0"
                  webkitallowfullscreen
                  mozallowfullscreen
                  allowfullscreen
                  className="loom-frame"
                ></iframe>
              </div>
            </div>
          </section>
        </section>
      </main>
    </div>
  );
}
